### ISSUE TITLE
Setup of required data

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/COVID-Bouncer-Admin#11]
The Developer wants the admin to setup the required data on the first login. Only after setting these information, he is allowed to go to the dashboard.

**Acceptance criteria**
- Open Setup page on the first Login
- Open Setup each login if required data is not set
- Setup Page doesn't show up if the required data is set.
- Required Data: Master-Password

**Comment by mirkopleli** [comment]
What exactly do you mean by this? The required collections are generated automatically during a sign-in.

**Comment by stritti** [comment]
For example the initial setup of configuration collection.

**Comment by chrisWolter** [comment]
This is done automatically by firebase if you add something to a none existing collection. [See first comment](https://stackoverflow.com/questions/55728065/how-to-create-empty-collection-in-firestore-swift)

**Comment by stritti** [comment]
Yes, but some entries have to be set up for working frontend. I think of somehow guided setup to define basically required data to be able to start frontend then.

**Comment by chrisWolter** [comment]
Which entries do we need for the frontend to work?

**Comment by chrisWolter** [comment]
The only point I see is that you can't get away from the Config page the first time if special data is not set, like the Master Password.
